"""policy_approval

Revision ID: 0005
Revises: 0004_tool_hub
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0005_policy_approval"
down_revision = "0004_tool_hub"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_policies_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policies")),
        sa.UniqueConstraint(
            "organization_id", "name", "version", name=op.f("uq_policies_organization_id")
        ),
    )
    op.create_table(
        "run_checkpoints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("runtime_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checkpoint_schema_version", sa.Integer(), nullable=False),
        sa.Column("runtime_build_version", sa.String(length=100), nullable=False),
        sa.Column("last_event_sequence", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_checkpoints_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_checkpoints")),
        sa.UniqueConstraint("run_id", "state_version", name=op.f("uq_run_checkpoints_run_id")),
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("tool_call_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("requested_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING','APPROVED','DENIED','EXPIRED')", name=op.f("ck_approvals_status")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_approvals_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"], ["policies.id"], name=op.f("fk_approvals_policy_id_policies")
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_approvals_run_id_runs")),
        sa.ForeignKeyConstraint(
            ["tool_call_id"], ["tool_calls.id"], name=op.f("fk_approvals_tool_call_id_tool_calls")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint("tool_call_id", name=op.f("uq_approvals_tool_call_id")),
    )
    op.create_index(op.f("ix_approvals_run_id"), "approvals", ["run_id"], unique=False)
    op.create_table(
        "demo_refunds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("tool_call_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("customer_id", sa.String(length=100), nullable=False),
        sa.Column("amount_usd", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_demo_refunds_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["tool_calls.id"],
            name=op.f("fk_demo_refunds_tool_call_id_tool_calls"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demo_refunds")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_demo_refunds_idempotency_key")),
        sa.UniqueConstraint("tool_call_id", name=op.f("uq_demo_refunds_tool_call_id")),
    )
    op.drop_constraint(op.f("ck_tool_calls_status"), "tool_calls", type_="check")
    op.create_check_constraint(
        "status",
        "tool_calls",
        "status IN ('WAITING_FOR_APPROVAL','RUNNING','COMPLETED','DENIED','FAILED','TIMED_OUT')",
    )
    op.execute("""
        CREATE FUNCTION forge_phase5_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'Immutable phase 5 record'; END $$
    """)
    for table in ("policies", "run_checkpoints"):
        op.execute(
            f"CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forge_phase5_immutable()"
        )
        op.execute(
            f"CREATE TRIGGER immutable_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION forge_phase5_immutable()"
        )
    op.execute("""
        CREATE FUNCTION forge_approval_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'INSERT' THEN
            IF NOT EXISTS (
              SELECT 1 FROM runs r JOIN tool_calls t ON t.run_id=r.id
              JOIN policies p ON p.id=NEW.policy_id
              WHERE r.id=NEW.run_id AND r.organization_id=NEW.organization_id
              AND p.organization_id=r.organization_id AND t.id=NEW.tool_call_id
              AND t.request_hash=NEW.request_hash AND t.arguments=NEW.requested_payload
            ) THEN RAISE EXCEPTION 'Approval binding mismatch'; END IF;
            IF NEW.status <> 'PENDING' THEN
              RAISE EXCEPTION 'Approval must begin pending';
            END IF;
          ELSE
            IF (to_jsonb(OLD) - ARRAY['status','reviewed_by','reviewed_at','decision_reason'])
              IS DISTINCT FROM
              (to_jsonb(NEW) - ARRAY['status','reviewed_by','reviewed_at','decision_reason'])
              OR OLD.status <> 'PENDING' THEN
              RAISE EXCEPTION 'Immutable approval evidence';
            END IF;
            IF NEW.status IN ('APPROVED','DENIED') AND
              (NEW.reviewed_by IS NULL OR NEW.reviewed_at IS NULL
                OR NEW.decision_reason IS NULL) THEN
              RAISE EXCEPTION 'Reviewer evidence required';
            END IF;
          END IF;
          RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER approval_guard BEFORE INSERT OR UPDATE ON approvals "
        "FOR EACH ROW EXECUTE FUNCTION forge_approval_guard()"
    )
    op.execute(
        "CREATE TRIGGER approval_delete_guard BEFORE DELETE ON approvals "
        "FOR EACH ROW EXECUTE FUNCTION forge_phase5_immutable()"
    )
    op.execute(
        "CREATE TRIGGER approval_truncate_guard BEFORE TRUNCATE ON approvals "
        "FOR EACH STATEMENT EXECUTE FUNCTION forge_phase5_immutable()"
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_tool_calls_status"), "tool_calls", type_="check")
    op.execute(
        "UPDATE tool_calls SET status='DENIED', "
        'error=\'{"code":"APPROVAL_MIGRATION_DOWNGRADE"}\'::jsonb '
        "WHERE status='WAITING_FOR_APPROVAL'"
    )
    op.create_check_constraint(
        "status", "tool_calls", "status IN ('RUNNING','COMPLETED','DENIED','FAILED','TIMED_OUT')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("demo_refunds")
    op.drop_index(op.f("ix_approvals_run_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_table("run_checkpoints")
    op.drop_table("policies")
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION forge_approval_guard()")
    op.execute("DROP FUNCTION forge_phase5_immutable()")
