"""durability

Revision ID: 0006_durability
Revises: 0005_policy_approval
"""

import sqlalchemy as sa
from alembic import op

revision = "0006_durability"
down_revision = "0005_policy_approval"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_controls",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_run_controls_run_id_runs")),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_run_controls")),
    )
    op.create_table(
        "run_outbox",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_run_outbox_run_id_runs")),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_run_outbox")),
    )
    op.create_index("ix_run_outbox_due", "run_outbox", ["completed", "available_at"], unique=False)
    op.add_column("runs", sa.Column("retry_of_run_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_runs_retry_of_run_id_runs"), "runs", "runs", ["retry_of_run_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_runs_retry_of_run_id_runs"), "runs", type_="foreignkey")
    op.drop_column("runs", "retry_of_run_id")
    op.drop_index("ix_run_outbox_due", table_name="run_outbox")
    op.drop_table("run_outbox")
    op.drop_table("run_controls")
    # ### end Alembic commands ###
